#!/usr/bin/env python3
"""Generate docs/data_dictionary.md from the live warehouse schema.

The dictionary is joined from two places: the schema DuckDB actually built,
and the prose in ``config/model_docs.yml``. Nothing is transcribed by hand, so
the published dictionary cannot drift from the warehouse.

Documentation drift is treated as a build error: if a dimension or fact column
has no description, this script exits non-zero and names the column. Reporting
marts are derived and mostly inherit their columns from the star, so their
columns are listed with types but do not require prose.

    python scripts/build_data_dictionary.py
"""

from __future__ import annotations

import sys
from datetime import UTC, datetime
from pathlib import Path

import duckdb
import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from pipelines.config import CONFIG_DIR, DOCS_DIR, paths  # noqa: E402

MODEL_DOCS = CONFIG_DIR / "model_docs.yml"
OUTPUT = DOCS_DIR / "data_dictionary.md"

# Layers whose columns must be documented, in the order they appear.
LAYER_ORDER = ["Dimension", "Fact", "Reporting mart", "Staging view", "Metadata"]
DESCRIPTIONS_REQUIRED = {"Dimension", "Fact"}


def live_schema(connection) -> dict[str, list[tuple[str, str]]]:
    """Columns of every non-system object in the warehouse, in ordinal order."""
    rows = connection.execute(
        """
        SELECT table_name, column_name, data_type
        FROM duckdb_columns()
        WHERE schema_name = 'main' AND NOT internal
        ORDER BY table_name, column_index
        """
    ).fetchall()
    schema: dict[str, list[tuple[str, str]]] = {}
    for table, column, data_type in rows:
        schema.setdefault(table, []).append((column, data_type))
    return schema


def row_counts(connection, tables: list[str]) -> dict[str, int]:
    counts = {}
    for table in tables:
        try:
            counts[table] = connection.execute(f"SELECT count(*) FROM {table}").fetchone()[0]
        except duckdb.Error:
            counts[table] = -1
    return counts


def main() -> int:
    database = paths().database
    if not database.exists():
        print(f"No warehouse at {database}. Run `python -m pipelines.cli all` first.")
        return 2

    docs = (yaml.safe_load(MODEL_DOCS.read_text()) or {}).get("models") or {}
    connection = duckdb.connect(str(database), read_only=True)
    try:
        schema = live_schema(connection)
        counts = row_counts(connection, list(schema))
    finally:
        connection.close()

    documented = [name for name in docs if name in schema]
    undocumented_models = sorted(
        set(schema)
        - set(docs)
        - {"raw_hospital_activity", "raw_iso_countries", "raw_population", "raw_location_overrides"}
    )
    problems: list[str] = [
        f"model {name} exists but is not documented" for name in undocumented_models
    ]

    for name in documented:
        entry = docs[name]
        if entry.get("layer") not in DESCRIPTIONS_REQUIRED:
            continue
        described = entry.get("columns") or {}
        for column, _ in schema[name]:
            if column not in described:
                problems.append(f"{name}.{column} has no description in {MODEL_DOCS.name}")
        for column in described:
            if column not in {c for c, _ in schema[name]}:
                problems.append(f"{name}.{column} is documented but no longer exists")

    if problems:
        print("Data dictionary is out of date:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        return 1

    built = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Data dictionary",
        "",
        "<!-- Generated by scripts/build_data_dictionary.py - do not edit by hand. -->",
        "<!-- Prose lives in config/model_docs.yml; the schema comes from the warehouse. -->",
        "",
        f"Generated {built} from `{database.name}`.",
        "",
        "Column descriptions are required for every dimension and fact column; the",
        "generator fails the build if one is missing. Reporting marts inherit most of",
        "their columns from the star and are listed with types.",
        "",
        "## Contents",
        "",
    ]

    by_layer: dict[str, list[str]] = {}
    for name in documented:
        by_layer.setdefault(docs[name].get("layer", "Other"), []).append(name)

    for layer in LAYER_ORDER:
        for name in sorted(by_layer.get(layer, [])):
            lines.append(f"- [`{name}`](#{name.replace('_', '-')}) — {layer.lower()}")
    lines.append("")

    for layer in LAYER_ORDER:
        names = sorted(by_layer.get(layer, []))
        if not names:
            continue
        lines += [f"## {layer}s" if not layer.endswith("s") else f"## {layer}", ""]
        for name in names:
            entry = docs[name]
            count = counts.get(name, -1)
            lines += [
                f"### {name}",
                "",
                " ".join((entry.get("description") or "").split()),
                "",
                f"- **Layer** — {entry.get('layer')}",
                f"- **Grain** — {' '.join((entry.get('grain') or 'not declared').split())}",
                f"- **Rows** — {count:,}" if count >= 0 else "- **Rows** — n/a",
                "",
                "| Column | Type | Description |",
                "| --- | --- | --- |",
            ]
            described = entry.get("columns") or {}
            for column, data_type in schema[name]:
                text = " ".join((described.get(column) or "").split()) or "—"
                lines.append(f"| `{column}` | `{data_type}` | {text} |")
            lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    total_columns = sum(len(schema[n]) for n in documented)
    print(f"{OUTPUT}: {len(documented)} models, {total_columns} columns")
    return 0


if __name__ == "__main__":
    sys.exit(main())
